package auth

import (
	"context"
	"log/slog"

	"github.com/MauroRaya/bike-rental-api/modules/jwt"
	repo "github.com/MauroRaya/bike-rental-api/sqlc/autogenerated"
	"golang.org/x/crypto/bcrypt"
)

type service struct {
	repo      repo.Querier
	jwtSecret string
}

type Service interface {
	SignUp(
		ctx context.Context,
		email string,
		password string,
	) (repo.CreateUserRow, error)

	SignIn(
		ctx context.Context,
		email string,
		password string,
	) (string, error)
}

func NewService(repo repo.Querier, jwtSecret string) Service {
	return &service{repo, jwtSecret}
}

func (s *service) SignUp(
	ctx context.Context,
	email string,
	password string,
) (repo.CreateUserRow, error) {
	hash, err := bcrypt.GenerateFromPassword(
		[]byte(password),
		bcrypt.DefaultCost,
	)
	if err != nil {
		slog.Error("failed to generate hash", "error", err)
		return repo.CreateUserRow{}, err
	}

	user, err := s.repo.CreateUser(ctx, repo.CreateUserParams{
		Email: email,
		Hash:  string(hash),
	})
	if err != nil {
		slog.Error("failed to create user", "error", err)
		return user, err
	}

	return user, nil
}

func (s *service) SignIn(
	ctx context.Context,
	email string,
	password string,
) (string, error) {
	user, err := s.repo.FindUserByEmail(ctx, email)
	if err != nil {
		slog.Error("failed to find user by email", "error", err)
		return "", err
	}

	if err = bcrypt.CompareHashAndPassword(
		[]byte(user.Hash),
		[]byte(password),
	); err != nil {
		slog.Error("invalid credentials", "error", err)
		return "", err
	}

	token, err := jwt.CreateToken(user, s.jwtSecret)
	if err != nil {
		slog.Error("failed to create jwt token", "error", err)
		return "", err
	}

	return token, nil
}
