package jwt

import (
	"log/slog"

	repo "github.com/MauroRaya/bike-rental-api/sqlc/autogenerated"
	"github.com/golang-jwt/jwt/v5"
)

func CreateToken(user repo.User, jwtSecret string) (string, error) {
	claims := jwt.MapClaims{
		"id":    user.ID,
		"email": user.Email,
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)

	tokenString, err := token.SignedString([]byte(jwtSecret))
	if err != nil {
		slog.Error("failed to sign jwt token", "error", err)
		return "", nil
	}

	return tokenString, nil
}
