// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bike": {
            "get": {
                "description": "get all bikes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bikes"
                ],
                "summary": "List bikes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/bike.Bike"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "create a new bike",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bikes"
                ],
                "summary": "Create bike",
                "parameters": [
                    {
                        "description": "Bike payload",
                        "name": "bike",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bike.CreateBike"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/bike.Bike"
                        }
                    },
                    "422": {
                        "description": "invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "unexpected error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/bike/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bikes"
                ],
                "summary": "Get bike by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Bike ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bike.Bike"
                        }
                    },
                    "422": {
                        "description": "invalid id",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "update an existing bike",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bikes"
                ],
                "summary": "Update bike",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Bike ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Bike payload",
                        "name": "bike",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bike.UpdateBike"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bike.Bike"
                        }
                    },
                    "422": {
                        "description": "invalid id or request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "unexpected error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bike.Bike": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "price_per_hour": {
                    "type": "integer"
                },
                "rented_at": {
                    "type": "string"
                },
                "rented_until": {
                    "type": "string"
                }
            }
        },
        "bike.CreateBike": {
            "type": "object",
            "properties": {
                "model": {
                    "type": "string"
                },
                "price_per_hour": {
                    "type": "integer"
                },
                "rented_at": {
                    "type": "string"
                },
                "rented_until": {
                    "type": "string"
                }
            }
        },
        "bike.UpdateBike": {
            "type": "object",
            "properties": {
                "model": {
                    "type": "string"
                },
                "price_per_hour": {
                    "type": "integer"
                },
                "rented_at": {
                    "type": "string"
                },
                "rented_until": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Bike Rental API",
	Description:      "This is a bike rental service API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
