basePath: /
definitions:
  auth.SignInParams:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  auth.SignInResponse:
    properties:
      token:
        type: string
    type: object
  auth.SignUpParams:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  pgtype.InfinityModifier:
    enum:
    - 1
    - 0
    - -1
    format: int32
    type: integer
    x-enum-varnames:
    - Infinity
    - Finite
    - NegativeInfinity
  pgtype.Timestamp:
    properties:
      infinityModifier:
        $ref: '#/definitions/pgtype.InfinityModifier'
      time:
        description: Time zone will be ignored when encoding to PostgreSQL.
        type: string
      valid:
        type: boolean
    type: object
  repo.Bike:
    properties:
      created_at:
        $ref: '#/definitions/pgtype.Timestamp'
      id:
        type: integer
      model:
        type: string
      price_per_hour:
        type: integer
      rented_at:
        $ref: '#/definitions/pgtype.Timestamp'
      rented_until:
        $ref: '#/definitions/pgtype.Timestamp'
    type: object
  repo.CreateBikeParams:
    properties:
      model:
        type: string
      price_per_hour:
        type: integer
      rented_at:
        $ref: '#/definitions/pgtype.Timestamp'
      rented_until:
        $ref: '#/definitions/pgtype.Timestamp'
    type: object
  repo.CreateUserRow:
    properties:
      email:
        type: string
      id:
        type: integer
    type: object
  repo.UpdateBikeParams:
    properties:
      id:
        type: integer
      model:
        type: string
      price_per_hour:
        type: integer
      rented_at:
        $ref: '#/definitions/pgtype.Timestamp'
      rented_until:
        $ref: '#/definitions/pgtype.Timestamp'
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a bike rental service API.
  title: Bike Rental API
  version: "1.0"
paths:
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Authenticate user
      parameters:
      - description: Sign in payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.SignInParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.SignInResponse'
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Sign in
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: Sign up payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.SignUpParams'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/repo.CreateUserRow'
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Sign up
      tags:
      - auth
  /bike:
    get:
      description: Get all bikes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/repo.Bike'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: List bikes
      tags:
      - bike
    post:
      consumes:
      - application/json
      description: Create a new bike
      parameters:
      - description: Bike payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/repo.CreateBikeParams'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/repo.Bike'
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create bike
      tags:
      - bike
  /bike/{id}:
    get:
      description: Get a bike by ID
      parameters:
      - description: Bike ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repo.Bike'
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Find bike by ID
      tags:
      - bike
    put:
      consumes:
      - application/json
      description: Update a bike
      parameters:
      - description: Bike ID
        in: path
        name: id
        required: true
        type: integer
      - description: Bike payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/repo.UpdateBikeParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repo.Bike'
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update bike
      tags:
      - bike
swagger: "2.0"
